config/routes.rb
Rails.application.routes.draw do

  post 'pay2go/return'
  post 'pay2go/notify'

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    resources :events
  end

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :orders do
    member do
      post :checkout_pay2go
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/events/first" => "events#first"

  get "/ubikes" => "ubikes#ubikes_data"

  get "/ajax" => "ajaxtest#ajax"
  get "/ajaxtest" => "ajaxtest#ajaxtest"

  resources :events do
    resource :location, :controller => "event_locations"
    resources :attendees, :controller => "event_attendees"
    resources :likes

    member do
      post :subscribe
      post :unsubscribe
    end

    collection do
      get :latest

      post :bulk_update

    end
    member do
      get :dashboard
      post :join
      post :withdraw
    end
  end

  namespace :admin do
    resources :events # , :controller=> "admin::events"(是預設值可省略)
    resources :orders
  end

  resources :people

  get "/welcome/say_helliii" => "welcome#say"
  get "welcome" => "welcome#index"

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user

  has_one :location
  validates_presence_of :name
  has_many :attendees
  belongs_to :category
  accepts_nested_attributes_for :location, :allow_destroy => true, :reject_if => :all_blank
  has_many :event_groupships
  has_many :groups, :through => :event_groupships

  has_many :users, through: :memberships
  has_many :memberships

  has_many :likes
  has_many :like_users, :through => :likes, :source => :user

  has_many :subscriptions
  has_many :subscribed_users, :through => :subscriptions, :source => :user

  def find_like_by(user)
    self.likes.find_by_user_id( user.id )
  end

  def find_subscription_by(user)
     self.subscriptions.find_by_user_id( user.id )
  end

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin
  # before_action :authenticate

  layout "admin"

  def index
    @event = Event.all
  end

  protected

  def check_admin
    unless current_user.admin?
      raise ActiveRecord::RecordNotFound
      # redirect_to root_path # 最好不要出現警告 讓它自動忽略 不要讓人發現是後台
    end
  end

  # def authenticate
  #   authenticate_or_request_with_http_basic do |user_name, password|
  #     user_name == "username" && password == "password"
  #   end
  # end

end

app/controllers/api_v1/events_controller.rb
class ApiV1::EventsController < ApiController

  def index
    @events = Event.page( params[:page] )
  end

  def show
    @event = Event.find(params[:id])
    # show.json.jbuilder
  end

  def create
    @event = Event.new( :name => params[:name],
                       :description => params[:description] )

    if @event.save
      render :json => { :id => @event.id }
    else
      render :json => { :message => "failed", :errors => @event.errors }, :status => 400
    end
  end

  def update
    @event = Event.find( params[:id] )

    if @event.update( :name => params[:name],
        :description => params[:description] )

      render :json => { :id => @event.id }
    else
      render :json => { :message => "failed", :errors => @event.errors }, :status => 400
    end
  end

  def destroy
    @topic = Topic.find( params[:id] )
    @topic.destroy

    render :json => { :message => "OK" }
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  before_action :set_event, :only => [:show, :edit, :update, :destroy]
  # GET /events/index
  # GET /events
  def index



    # if params["foo"]
    #   @events = Event.page(params[:page]).per(2)
    # elsif params["foo1"]
    #   @events = Event.page(params[:page]).per(3)
    # elsif
    # @events = Event.page( params[:page]).per(10)
    # end

    prepare_variable_for_index_template

    #Rails.logger.debug("XXXXXXX:" + "#{@events.count}")

    respond_to do |format|
      format.html #index.html.erb
      format.xml {
        render :xml => @events.to_xml
      }
      format.json{
        render :json => @events.to_json
      }
      format.atom{
        @feed_title = "My event list"
      } #index.atom.builder
    end
  end

  def latest
    @events = Event.order("id DESC").limit(3)
  end

  def show

    @page_title = @event.name
    respond_to do |format|
      format.html { @page_title = @event.name } # show.html.erb
      format.xml # show.xml.builder
      format.json { render :json => { id: @event.id, name: @event.name, created_at: @event.created_at }.to_json }
    end


    UserMailer.delay_until(6.seconds.from_now).notify_comment(@event, @event.user)

  end

  def dashboard
    @event = Event.find(params[:id])
  end

  def edit
    @events = Event.page(params[:page]).per(5)
    render :index
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    @event.user = current_user

    if @event.save
      flash[:notice] = "新增成功"
      redirect_to events_path
    else
      render :action => :new
    end
  end

  def update
    if params[:_remove_logo]=="1"
      @event.logo = nil
    end

    if @event.update(event_params)

      flash[:notice] = "update 成功"

      redirect_to event_path(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @event.destroy

    flash[:alert] = "delete成功"

    redirect_to events_path(:page => params[:page])

  end


  # POST /events/bulk_update

  def bulk_update
    ids = Array(params[:ids])
    events = ids.map{ |i| Event.find_by_id(i) }.compact

    if params[:commit] == "Publish"
      events.each{ |e| e.update( :status => "published" ) }
    elsif params[:commit] == "Delete"
      events.each{ |e| e.destroy }
    end

    redirect_to :back
  end


  # POST /events/bulk_delete
  #
  # def bulk_delete
  #   Event.destroy_all
  #
  #    redirect_to :back
  #  end

  #新的方法 要在routes.rb 加在resource之前（上到下讀取）
  # def first
  #   Event.first

  #   redirect_to events_path
  # end


  def join
    @event = Event.find(params[:id])
    Membership.find_or_create_by(:event => @event, :user => current_user)
    redirect_to :back
  end

  def withdraw
    @event = Event.find(params[:id])
    @membership = Membership.find_by(:event => @event, :user => current_user)
    @membership.destroy if @membership
    redirect_to :back
  end

  def subscribe
    @event = Event.find( params[:id] )

    subscription = @event.find_subscription_by(current_user)
    if subscription
      # do nothing
    else
      @subscription = @event.subscriptions.create!( :user => current_user )
    end

    redirect_to :back
  end
  def unsubscribe
    @event = Event.find( params[:id] )

    subscription = @event.find_subscription_by(current_user)
    subscription.destroy

    redirect_to :back
  end


  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name,:logo, :description,:category_id,:status,:location_attributes => [:id, :name, :_destroy],:group_ids => []  )
  end

  def prepare_variable_for_index_template

    @users = User.all
    @event = Event.new

    if params[:keyword]
      @events = Event.where( [ "name like ?", "%#{params[:keyword]}%" ] )
    else
      @events = Event.all
    end

    if params[:order]
      sort_by = (params[:order] == 'name') ? 'name' : 'id'
      @events = @events.order(sort_by)
    end

    @events = @events.page(params[:page]).per(5)

  end


end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def setup_event(event)
    event.build_location unless event.location
    event
  end
end

app/views/events/123.html.erb
<%= form_for setup_event(@event), :url => events_path do |f| %>

  <div class="f rm-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>


<% end %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= f.collection_select(:category_id, Category.all, :id, :name) %>

<%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>

<div class="form-group">
  <%= f.file_field :logo %>

  <% if @event.logo.exists? %>
    <%= check_box_tag "_remove_logo", "1" %> Remove logo
  <% end %>
</div>

<%= f.fields_for :location do |location_form| %>
  <p>
  <%= location_form.label :name, "11Location Name" %>
  <%= location_form.text_field :name %>

  <% unless location_form.object.new_record? %>
    <%= location_form.label :_destroy, 'Remove:' %>
    <%= location_form.check_box :_destroy %>
  <% end %>
  </p>
<% end %>


<div class="form-group">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :status, "Status" %>
  <%= f.select :status, [["Published", "Published"],["Draft","Draft"]] %>
</div>

app/views/events/_like.html.erb
<h2><%= @event.likes.count %></h2>
<% if like %>
  <%= link_to "Unlike", event_like_path(@event, like), :remote => true, :method => :delete, :class => "btn btn-primary btn-lg" %>
<% else %>
  <%= link_to "Like", event_likes_path(@event), :remote => true, :method => :post, :class => "btn btn-primary btn-lg" %>
<% end %>

app/views/events/dashboard.html.erb
<%= @event.name %>'s Dashboard

app/views/events/edit.html.erb
<%= form_for setup_event(@event), :url => event_path(@event), :method => :patch , :class => "form" do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>
  <%# 會自動找＿開頭的html.erb檔案  %>


  <%= f.submit "Update", :class => "btn btn-primary" %>
<% end %>

app/views/events/index.html.erb
<h1><%= t("Event list") %></h1>

<%#= debug(@events[0]) %> <%#debug 印出events 第一筆物件資料 %>

<%= @users.last.username%>
<%= @users.last.gender%>
<%= image_tag (@users.last.fb_pic) %>

<p>
<%= link_to "Latest event", latest_events_path %>
</p>
<p>
<%= link_to "Ajax", ajax_path %>
</p>

<%= form_for setup_event(@event) do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Create", :class => "btn btn-primary" %>

<% end %>

<%= form_tag events_path, :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>



<%= form_tag bulk_update_events_path do %>

  <%= link_to 'Sort by Name', events_path( :order => "name") %>
  <%= link_to 'Sort by Default', events_path %>

  <table class="table">
    <% @events.each do |e| %>

      <tr>
        <td>
          <%= check_box_tag "ids[]", e.id, false %>
          <%= e.name %>
        </td>

        <td>
          <%= e.user.try(:short_name) %>
        </td>

        <td>
          <%#= link_to "Show", :controller => "events", :action=> "show",:id=> e %>
          <%= e.created_at %>
          <%= link_to "Show", event_path(e), :class => "btn btn-primary" %>
          <%= link_to "Dashboard", dashboard_event_path(e), :class => "btn btn-primary" %>
          <%= link_to "Attendee List", event_attendees_path(e), :class => "btn btn-primary" %>
          <%= link_to "Get XML", event_path(e, :format => :xml) , :class => "btn btn-default" %>
          <%= link_to "Get JSON", event_path(e, :format => :json) , :class => "btn btn-default" %>
          <%= link_to 'location', event_location_path(e) %>
          <%= link_to "Edit", edit_event_path(e) , :class => "btn btn-default" %>
          <%= link_to "Delete", event_path(e, :page => params[:page]), :method => :delete , :class => "btn btn-danger" %>
        </td>
      </tr>

    <% end %>
  </table>

  <%#= button_to "Delete All", bulk_delete_events_path, :method => :post %>
  <!-- # button_to 也是html form標籤 因為form裡面不能包form 所以用submit_tag-->
  <%= submit_tag "Delete" %>
  <%= submit_tag "Publish" %>

<% end %>

<%= link_to 'New Event', new_event_path %>
<%= link_to "Atom feed", events_path(:format => :atom) %>

<%= paginate @events %>



<%= link_to "first", events_path(:foo=>1)%>
<%= link_to "first1", events_path(:foo1=>:woo1)%>

app/views/events/latest.html.erb
<% @events.each do |event| %>
  <%= event.name %>
<% end  %>

app/views/events/new.html.erb
<%= form_for setup_event(@event), :url => events_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>


  <%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<p><%= @event.status %></p>

<% like = @event.find_like_by(current_user) %>

<%# html的方法 %>
<h2><%#= @event.likes.count %></h2>
<%# if like %>
<%#= link_to "Unlike", event_like_path(@event, like), :method => :delete, :class => "btn btn-primary btn-lg" %>
<%# else %>
<%#= link_to "Like", event_likes_path(@event), :method => :post, :class => "btn btn-primary btn-lg" %>
<%# end %>

<%# ajax的方法 %>
<div id="like-area">
  <%= render :partial => "like", :locals => { :like => like } %>
</div>

<% subscription = @event.find_subscription_by(current_user) %>
 <% if subscription %>
   <%= link_to "Unsubscribe", unsubscribe_event_path(@event), :method => :post, :class => "btn btn-primary btn-lg" %>
 <% else %>
   <%= link_to "Subscribe", subscribe_event_path(@event), :method => :post, :class => "btn btn-primary btn-lg" %>
 <% end %>




<p>Category: <%= @event.category.try(:name) %><p>

<%= simple_format(@event.description) %>

<% if @event.logo.exists?  %>
  <%= image_tag (@event.logo.url(:thumb)) %>
<%else %>
  None
<% end  %>

<p>Group:
<% @event.groups.each do |g| %>
  <%= g.name %>
<% end %>
</p>

<% @event.users.each do |user| %>
  <p><%= user.email %></p>
<% end %>


<%= button_to "Join", join_event_path(@event) %>
<%= button_to "Withdraw", withdraw_event_path(@event), method: :post %>


<p><%= link_to 'Back to index',events_path %></p>